import { writeFile, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ? pathToFileURL(process.env.PLAYWRIGHT_MODULE).href : 'playwright');
const output = process.env.SHORTSFORGE_TEST_OUTPUT || path.join(tmpdir(), 'shortsforge-check'); await mkdir(output, { recursive: true });
process.env.TEMP = output;
process.env.TMP = output;
await writeFile(path.join(output, 'fixture.gif'), Buffer.from('R0lGODlhMAAwAIEAAP8AAAAAAAAAAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh+QQAMgAAACwAAAAAMAAwAAAITwABCBxIsKDBgwgTKlzIsKHDhxAjSpxIsaLFixgzatzIsaPHjyBDihxJsqTJkyhTqlzJsqXLlzBjypxJs6bNmzhz6tzJs6fPn0CDCh2qMSAAIfkEATIAAQAsAAAAADAAMACBAAD/AAAAAAAAAAAACE8AAQgcSLCgwYMIEypcyLChw4cQI0qcSLGixYsYM2rcyLGjx48gQ4ocSbKkyZMoU6pcybKly5cwY8qcSbOmzZs4c+rcybOnz59AgwodqjEgADs=', 'base64'));
const browser = await chromium.launch({ executablePath: process.env.CHROME_EXECUTABLE, headless: true, args: ['--autoplay-policy=no-user-gesture-required'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 1100 }, acceptDownloads: true });
const errors = []; page.on('pageerror', error => errors.push(error.message));
try {
  await page.goto('http://127.0.0.1:5178/');
  await page.route('**/test-fixture.gif', route => route.fulfill({ path: output+'/fixture.gif', contentType:'image/gif' }));
  const tts = await page.request.post('http://127.0.0.1:5178/api/tts', { data: { texto: 'El dragón encontró el balón.' }, timeout: 100000 });
  const live = await tts.json();
  console.log('Live TTS:', JSON.stringify({ status: tts.status(), words: live.words?.length, error: live.error }));
  // Deterministic media fixture isolates browser rendering from external provider outages.
  const fixture = await page.evaluate(() => {
    const rate = 8000, count = 8000; const bytes = new ArrayBuffer(44 + count * 2), v = new DataView(bytes);
    const text = (offset, value) => [...value].forEach((c, i) => v.setUint8(offset+i,c.charCodeAt(0)));
    text(0,'RIFF'); v.setUint32(4,36+count*2,true); text(8,'WAVE'); text(12,'fmt '); v.setUint32(16,16,true); v.setUint16(20,1,true); v.setUint16(22,1,true); v.setUint32(24,rate,true); v.setUint32(28,rate*2,true); v.setUint16(32,2,true); v.setUint16(34,16,true); text(36,'data'); v.setUint32(40,count*2,true);
    for(let i=0;i<count;i++) v.setInt16(44+i*2,Math.sin(i/rate*440*Math.PI*2)*4000,true);
    const audio = 'data:audio/wav;base64,'+btoa(String.fromCharCode(...new Uint8Array(bytes)));
    const c=document.createElement('canvas'); c.width=1080;c.height=1920; const ctx=c.getContext('2d');ctx.fillStyle='#153c50';ctx.fillRect(0,0,1080,1920);ctx.fillStyle='#facc15';ctx.fillRect(200,500,680,600);
    return { audio, image:c.toDataURL() };
  });
  await page.route('**/api/tts', route => route.fulfill({ json: {url:fixture.audio,words:[{word:'Gol',start:0,end:0.6}]} }));
  await page.route('**/api/imagen', route => route.fulfill({ json: {url:fixture.image,fuente:'fixture'} }));
  let scriptRequests=0;
  await page.route('**/api/guion', route => { scriptRequests++; return route.fulfill({ json: { guion: { titulo:'Prueba de producción',hook:'Gol',cta:'',descripcion:'Ficción de prueba',hashtags:['#Shorts'],escenas:Array.from({length:6},()=>({narracion:'Gol',subtitulo:'Gol',prompt_imagen:'Castillo'})) } } }); });
  await page.getByRole('button', {name:'IA · Cualquier Tema',exact:false}).click();
  await page.getByLabel('Canal',{exact:true}).selectOption('Fútbol Medieval');
  await page.getByLabel('Duración',{exact:true}).selectOption('15');
  await page.getByLabel('Estilo del video').selectOption('humor');
  await page.getByRole('button',{name:'Generar todo automáticamente'}).click();
  await page.getByRole('heading',{name:'Estilos, memes y gráficos'}).waitFor({timeout:30000});
  await page.getByLabel('Tipo de gráfico').selectOption('reaction');
  await page.getByLabel('Texto de reacción').fill('¡GOLAZO!');
  await page.getByLabel('Efecto sonoro',{exact:true}).selectOption('comedy');
  await page.getByRole('button',{name:'Subtítulos por palabra',exact:true}).click();
  await page.screenshot({path:output+'/studio.png',fullPage:true});
  const download = page.waitForEvent('download', {timeout:30000});
  await page.getByRole('button',{name:'Exportar video (MP4 / WebM)',exact:true}).click();
  const file = await download; await file.saveAs(output+'/'+file.suggestedFilename());
  console.log('Export:',file.suggestedFilename());
  await page.waitForTimeout(900);
  await page.reload();
  await page.getByLabel('Biblioteca local').selectOption({label:'Fútbol Medieval · Prueba de producción'});
  await page.getByRole('heading',{name:'Estilos, memes y gráficos'}).waitFor();
  if (await page.getByLabel('Texto de reacción').inputValue() !== '¡GOLAZO!') throw new Error('Overlay was not saved');
  await page.getByLabel('Tipo de gráfico').selectOption('chart');
  await page.getByLabel('Porcentaje real').fill('72');
  await page.getByLabel('Descripción del dato').fill('Dato de prueba');
  const gifResult = await page.evaluate(async () => {
    const { loadGif, drawOverlay } = await import('/src/services/effects.ts');
    const response = await fetch('/test-fixture.gif');
    const blob = await response.blob();
    const url = URL.createObjectURL(blob); await loadGif(url);
    const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1920;const ctx=canvas.getContext('2d');
    const scene={overlay:{kind:'gif',url,start:0,duration:1.5}};
    drawOverlay(ctx,scene,0.25);const first=[...ctx.getImageData(500,930,1,1).data];
    ctx.clearRect(0,0,1080,1920);drawOverlay(ctx,scene,0.65);const second=[...ctx.getImageData(500,930,1,1).data];
    return {first,second};
  });
  if(JSON.stringify(gifResult.first)===JSON.stringify(gifResult.second)) throw new Error('GIF did not animate');
  await page.getByLabel('Tipo de gráfico').selectOption('gif');
  await page.getByLabel('Cargar GIF',{exact:true}).setInputFiles(output+'/fixture.gif');
  await page.getByLabel('Efecto sonoro',{exact:true}).selectOption('custom');
  const audioBytes=Buffer.from(fixture.audio.split(',')[1],'base64');
  await page.getByLabel('Cargar sonido',{exact:true}).setInputFiles({name:'effect.wav',mimeType:'audio/wav',buffer:audioBytes});
  await page.waitForTimeout(300);
  const gifDownload=page.waitForEvent('download',{timeout:30000});
  await page.getByRole('button',{name:'Exportar video (MP4 / WebM)',exact:true}).click();
  await (await gifDownload).saveAs(output+'/gif-custom.mp4');
  await page.unroute('**/api/tts');
  await page.route('**/api/tts',route=>route.fulfill({status:500,json:{error:'Error controlado de voz'}}));
  await page.getByRole('button',{name:'Exportar video (MP4 / WebM)',exact:true}).click();
  await page.getByRole('alert').filter({hasText:'Error controlado de voz'}).waitFor();
  console.log('PASS: GIF frames differ, custom audio export, explicit TTS failure');
  // Check that generated variants call the LLM for every angle.
  const count = await page.evaluate(async () => {
    const {generateFiveVariantsForTopic}=await import('/src/services/videoGeneratorEngine.ts');
    const projects=await generateFiveVariantsForTopic('Ficción de un torneo','Fútbol Medieval');return projects.length;
  });
  if(count!==5 || scriptRequests!==6) throw new Error('Variants did not call generator');
  console.log('PASS: automatic generation, effects, export, saved project, five real requests');
  console.log('Browser errors:',JSON.stringify(errors));
  if(errors.length) throw new Error('Browser runtime errors');
  await writeFile(output+'/results.json',JSON.stringify({liveTts:tts.status(),words:live.words?.length,export:file.suggestedFilename(),errors},null,2));
} finally { await browser.close(); }
